<a href="https://colab.research.google.com/github/Pgreddy5679/Breastcancerdectect/blob/main/Breast_Cancer_Dection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Breast Cancer Dectection**


In [4]:
import numpy as np
import sklearn.datasets

In [5]:
#getting the dataset
breast_cancer = sklearn.datasets.load_breast_cancer()

In [6]:
print(breast_cancer)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [7]:
X=breast_cancer.data
Y=breast_cancer.target

In [ ]:
print(X)
print(Y)

In [10]:
print(X.shape,Y.shape)

(569, 30) (569,)


Import data to the Pandas Data Frame

In [11]:
import pandas as pd


In [12]:
data =pd.DataFrame(breast_cancer.data,columns= breast_cancer.feature_names)

In [13]:
data['class']=breast_cancer.target

In [ ]:
data.head()

In [ ]:
data.describe()

In [ ]:
print(data['class'].value_counts())

In [ ]:
print(breast_cancer.target_names)

In [ ]:
data.groupby('class').mean()

0-Malignant
1-Benign

Train and Test split

In [20]:
from  sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [22]:
print(Y.shape,Y_train.shape,Y_train.shape)

(569,) (426,) (426,)


In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1)

In [24]:
print(Y.shape,Y_train.shape,Y_train.shape)

(569,) (512,) (512,)


In [25]:
print(Y.mean(),Y_train.mean(),Y_test.mean())

0.6274165202108963 0.623046875 0.6666666666666666


In [27]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,stratify=Y)
# test_size --> to specify the percentage of test data needed

In [28]:
print(Y.shape,Y_train.shape,Y_test.shape)

(569,) (512,) (57,)


In [31]:
print(Y.mean(),Y_train.mean(),Y_test.mean())

0.6274165202108963 0.626953125 0.631578947368421


In [34]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1 ,stratify=Y)
#stratify --> for correct distribution of data as of the original data

In [ ]:
print(Y.mean(),Y_train.mean(),Y_test.mean())

In [37]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1 ,stratify=Y,random_state=1)
#random_state --> specific split of data,each value of random_state splits the data diffrently

In [38]:
print(X.mean(),X_train.mean(),X_test.mean())

61.890712339519624 61.31637960106119 67.04963097269005


In [39]:
print(X_train)

[[1.490e+01 2.253e+01 1.021e+02 ... 2.475e-01 2.866e-01 1.155e-01]
 [1.205e+01 1.463e+01 7.804e+01 ... 6.548e-02 2.747e-01 8.301e-02]
 [1.311e+01 1.556e+01 8.721e+01 ... 1.986e-01 3.147e-01 1.405e-01]
 ...
 [1.258e+01 1.840e+01 7.983e+01 ... 8.772e-03 2.505e-01 6.431e-02]
 [1.349e+01 2.230e+01 8.691e+01 ... 1.282e-01 2.871e-01 6.917e-02]
 [1.919e+01 1.594e+01 1.263e+02 ... 1.777e-01 2.443e-01 6.251e-02]]


Logistic Regression

In [41]:
# import logistic Regression from sklearn
from sklearn.linear_model import LogisticRegression


In [42]:
classifier = LogisticRegression() # loading the logistic regression model  to the varaible "classifier"

In [43]:
classifier.fit?

In [44]:
# training the model on the training data
classifier.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

**Evaluation of the model**

In [45]:
#import accuracy_score
from sklearn.metrics import accuracy_score

In [49]:
prediction_on_training_data = classifier.predict(X_train)
accuracy_on_training_data = accuracy_score(Y_train,prediction_on_training_data)

In [50]:
print("Accuracy on training data : ",accuracy_on_training_data)

Accuracy on training data :  0.951171875


In [51]:
#predict on test_data
prediction_on_test_data = classifier.predict(X_test)
accuracy_on_test_data = accuracy_score(Y_test,prediction_on_test_data)

In [52]:
print("Accuracy on testing data : ",accuracy_on_test_data )

Accuracy on testing data :  0.9298245614035088


Dectecting whether the patient has breast cancer in benign or Malignant stage

In [55]:
input_data = (17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189)
# change the input_data to numpy_array to make prediction
input_data_as_numpy_array=np.asarray(input_data)
print(input_data)

# reshape the array as we are predicting the output for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

#prediction
prediction = classifier.predict(input_data_reshaped)
print(prediction) # return a list with element [0] if Malignant; returns a listwith elemenent[1],if benign
if (prediction[0]==0):
  print("The breast cancer is Malignant")
else:
  print("The breast cancer is Benign") 

(17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189)
[0]
The breast cancer is Malignant
